-- Verse - seed days with precomputed Bot paths (node scripts/gen-seed.js)
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-05', 1, 'crane', '[{"guess":"salet","fb":["absent","present","absent","present","absent"]},{"guess":"oread","fb":["absent","correct","present","present","absent"]},{"guess":"brace","fb":["absent","correct","correct","present","correct"]},{"guess":"crane","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-06', 2, 'plant', '[{"guess":"salet","fb":["absent","present","present","absent","correct"]},{"guess":"clapt","fb":["absent","correct","correct","present","correct"]},{"guess":"plait","fb":["correct","correct","correct","absent","correct"]},{"guess":"plant","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-07', 3, 'globe', '[{"guess":"salet","fb":["absent","absent","present","present","absent"]},{"guess":"reoil","fb":["absent","present","correct","absent","present"]},{"guess":"ploce","fb":["absent","correct","correct","absent","correct"]},{"guess":"glode","fb":["correct","correct","correct","absent","correct"]},{"guess":"globe","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-08', 4, 'storm', '[{"guess":"salet","fb":["correct","absent","absent","absent","present"]},{"guess":"stour","fb":["correct","correct","correct","absent","present"]},{"guess":"story","fb":["correct","correct","correct","correct","absent"]},{"guess":"storm","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-09', 5, 'brick', '[{"guess":"salet","fb":["absent","absent","absent","absent","absent"]},{"guess":"nidor","fb":["absent","present","absent","absent","present"]},{"guess":"crimp","fb":["present","correct","correct","absent","absent"]},{"guess":"brick","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-10', 6, 'mango', '[{"guess":"salet","fb":["absent","correct","absent","absent","absent"]},{"guess":"radio","fb":["absent","correct","absent","absent","correct"]},{"guess":"banco","fb":["absent","correct","correct","absent","correct"]},{"guess":"mango","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-11', 7, 'pearl', '[{"guess":"salet","fb":["absent","present","present","present","absent"]},{"guess":"realo","fb":["present","correct","correct","present","absent"]},{"guess":"learn","fb":["present","correct","correct","correct","absent"]},{"guess":"pearl","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-12', 8, 'vault', '[{"guess":"salet","fb":["absent","correct","present","absent","correct"]},{"guess":"dault","fb":["absent","correct","correct","correct","correct"]},{"guess":"hault","fb":["absent","correct","correct","correct","correct"]},{"guess":"gault","fb":["absent","correct","correct","correct","correct"]},{"guess":"fault","fb":["absent","correct","correct","correct","correct"]},{"guess":"vault","fb":["correct","correct","correct","correct","correct"]}]');
INSERT OR REPLACE INTO days (date, day_number, word, ai_path) VALUES ('2026-09-13', 9, 'choir', '[{"guess":"salet","fb":["absent","absent","absent","absent","absent"]},{"guess":"nidor","fb":["absent","present","absent","present","correct"]},{"guess":"choir","fb":["correct","correct","correct","correct","correct"]}]');
