# Beat the Bot - Cloudflare Pages project config.
name = "verse-game"
pages_build_output_dir = "public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "verse-game"
database_id = "cfcfa52c-9b82-43e7-b016-73e1b745efa4"
migrations_dir = "migrations"
